// Command genrules emits internal/intent/builtin_rules_gen.go from YAML rules.
package main

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/alibaba40core/clx/internal/intent"
)

func main() {
	root := findModuleRoot()
	if root == "" {
		fmt.Fprintln(os.Stderr, "go.mod not found")
		os.Exit(1)
	}

	fsys := os.DirFS(root)
	rules, err := intent.LoadRulesFromFS(fsys, "internal/builtin/rules")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	skills, err := intent.LoadSkillsFromFS(fsys, "internal/builtin/skills")
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	all := append(rules, skills...)

	data, err := json.Marshal(all)
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	var buf bytes.Buffer
	zw := gzip.NewWriter(&buf)
	if _, err := zw.Write(data); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := zw.Close(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	encoded := base64.StdEncoding.EncodeToString(buf.Bytes())

	outPath := filepath.Join(root, "internal", "intent", "builtin_rules_gen.go")
	out := fmt.Sprintf(`// Code generated by cmd/genrules; DO NOT EDIT.

package intent

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"sync"
)

const generatedRulesGzipB64 = %q

var (
	generatedOnce  sync.Once
	generatedRules []Rule
	generatedErr   error
)

func loadGeneratedBuiltinRules() ([]Rule, error) {
	generatedOnce.Do(func() {
		raw, err := base64.StdEncoding.DecodeString(generatedRulesGzipB64)
		if err != nil {
			generatedErr = err
			return
		}
		zr, err := gzip.NewReader(bytes.NewReader(raw))
		if err != nil {
			generatedErr = err
			return
		}
		defer zr.Close()
		if err := json.NewDecoder(zr).Decode(&generatedRules); err != nil {
			generatedErr = err
			return
		}
	})
	return generatedRules, generatedErr
}
`, encoded)

	if err := os.WriteFile(outPath, []byte(out), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("wrote", outPath)
}

func findModuleRoot() string {
	dir, err := os.Getwd()
	if err != nil {
		return ""
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return ""
		}
		dir = parent
	}
}
